# Generated by Django 5.1.3 on 2025-05-28 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCuerpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.PositiveIntegerField(blank=True, null=True)),
                ('ancho_hombros', models.PositiveIntegerField(blank=True, null=True)),
                ('pecho_espalda', models.PositiveIntegerField(blank=True, null=True)),
                ('cintura', models.PositiveIntegerField(blank=True, null=True)),
                ('busto', models.PositiveIntegerField(blank=True, null=True)),
                ('cadera', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assessment.evento')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assessment.lugar')),
                ('tipo_cuerpo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Assessment.tipocuerpo')),
            ],
        ),
    ]
