# Generated by Django 5.1.3 on 2025-06-18 02:29

import Assessment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assessment', '0007_categoriacalzadohombre_categoriainferiorhombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prendacalzadohombre',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=Assessment.models.ProfilePictureStorage, upload_to='prendas/calzado_hombre/'),
        ),
        migrations.AlterField(
            model_name='prendacalzadomujer',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=Assessment.models.ProfilePictureStorage, upload_to='prendas/calzado/'),
        ),
        migrations.AlterField(
            model_name='prendainferiorhombre',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=Assessment.models.ProfilePictureStorage, upload_to='prendas/inferior_hombre/'),
        ),
        migrations.AlterField(
            model_name='prendainferiormujer',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=Assessment.models.ProfilePictureStorage, upload_to='prendas/inferior/'),
        ),
        migrations.AlterField(
            model_name='prendasuperiorhombre',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=Assessment.models.ProfilePictureStorage, upload_to='prendas/superior_hombre/'),
        ),
        migrations.AlterField(
            model_name='prendasuperiormujer',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=Assessment.models.ProfilePictureStorage, upload_to='armario/superior_mujer/'),
        ),
    ]
